In [9]:
import numpy as np
import pandas as pd

In [4]:
A = np.array([[1, 12, 3],
              [8, 5, 6]])

B = np.array([[7, 3, 9],
              [10, 1, 2]])

vertical = np.vstack((A, B))
horizontal = np.hstack((A, B))

print("Vertical Stack:")
print(vertical)
print("Horizontal Stack:")
print(horizontal)

Vertical Stack:
[[ 1 12  3]
 [ 8  5  6]
 [ 7  3  9]
 [10  1  2]]
Horizontal Stack:
[[ 1 12  3  7  3  9]
 [ 8  5  6 10  1  2]]


In [6]:
common= np.intersect1d(A, B)
print("Common elements between arrays A and B:", common)

Common elements between arrays A and B: [1 3]


In [7]:
temp = A[(A >= 5) & (A <= 10)]
print("Numbers in A between 5 and 10:", temp)

Numbers in A between 5 and 10: [8 5 6]


In [8]:
data = np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', delimiter=',', dtype='float', usecols=[0, 1, 2, 3])

filtered_rows = data[(data[:, 2] > 1.5) & (data[:, 0] < 5.0)]
print("Filtered rows:\n", filtered_rows)

Filtered rows:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [33]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

filtered_rows = df.loc[::20, ['Manufacturer', 'Model', 'Type']]
print(filtered_rows)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [39]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
min_mean = df['Min.Price'].mean()
max_mean = df['Max.Price'].mean()
df['Min.Price'] = df['Min.Price'].fillna(min_mean)
df['Max.Price'] = df['Max.Price'].fillna(max_mean)

print(df[['Min.Price', 'Max.Price']].head())

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


In [40]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
filtered_rows = df[df.sum(axis=1) > 100]
print(filtered_rows)

     0   1   2   3
1   38  31  28  16
4   19  33  33  32
6   31  32  17  27
9   30  32  15  25
10  29  36  29  22
13  25  33  37  31
